# Header

menu:
  主页: /
  随笔: /tags/随笔/
  前端: /tags/前端/
  后端: /tags/后端/
  算法: /tags/算法/
# SubNav
subnav:
  github: "https://github.com/buxiaoxing"
  # weibo: "#"
  # zhihu: "#"
  #qq: "#"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  bilibili: "https://space.bilibili.com/504766102"
  #acfun: "#"
  mail: "mailto:budaxing@gmail.com"
  #facebook: "#"
  #google: "#"
  twitter: "https://twitter.com/BuDaxing"
  #linkedin: "#"
  rss: "atom.xml"

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: /

# Content

# 文章太长，截断按钮文字
excerpt_link: false
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: more
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 0
# 打赏wording
reward_wording: '谢谢你请我吃糖果'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay:
# 微信二维码图片地址
weixin:

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 1
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '目录，不存在的…'

# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /assets/img/favicon.ico

#你的头像url
avatar: /assets/img/avatar.jpg
author: 布小星
#是否开启分享
share_jia: false

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus；5、Gitment 6、valine 7、twikoo
#不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: false

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

#5、Gitment
gitment:
  enable: false
  owner: ''      #你的 GitHub ID
  repo: 'blogComments'          #存储评论的 repo
  oauth:
    client_id: '27f3d82ff7a40a30c214'           #client ID
    client_secret: '894452967ed1eee5721905c79e0b546e19affd24'       #client secret

#6、Valine https://valine.js.org
valine:
  enable: false
  appid: p4INyDk8UrxnksxAeVTejjf2-gzGzoHsz #Leancloud应用的appId
  appkey: 1atEstntPKh7wcTfpFhvw27x #Leancloud应用的appKey
  verify: false #验证码
  notify: false #评论回复提醒
  avatar: mm #评论列表头像样式：''/mm/identicon/monsterid/wavatar/retro/hide
  placeholder: Just go go #评论框占位符

#7、twikoo https://twikoo.js.org/
twikoo:
  enable: true
  envId: twikoo-1gbsuvyuc4fdd2b0 # 环境id

# 不蒜子访问量统计
busuanzi: 
  enable: true
  site_visit: true  # 站点访问量显示
  article_visit: true  # 文章访问量显示

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  gitee: https://gitee.com/buxiaoxing
  归类笔记: https://gitee.com/buxiaoxing/note
  个人简历: https://github.com/buxiaoxing/resume
  博客园: https://www.cnblogs.com/angle-yan/

aboutme: 我知道我终会死去<br/><br/>正如我知道明天的太阳会从东方升起<br/><br/><br/><br/>我只是希望在我垂死之际<br/><br/>除了回忆<br/><br/>还有别的东西帮我克服恐惧<br/><br/><br/><br/>比如这些笔记
